### Registrar un nuevo usuario
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "matias",
    "email": "matiasdsr@gmail.com",
    "password": "123123_Ms"
}


### Iniciar sesión con credenciales de usuario
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "matiasdsr@gmail.com",
    "password": "123123_Ms"
}


### Obtener informacion del usuario actual mediante cookies
GET http://localhost:5000/api/auth/me HTTP/1.1


### Cerrar sesión
GET http://localhost:5000/api/auth/logout HTTP/1.1


### Obtener perfiles
GET http://localhost:5000/api/profiles HTTP/1.1


### Crear un nuevo perfil
POST http://localhost:5000/api/profiles HTTP/1.1
content-type: application/json

{
    "name": "HECTOR3",
    "type": "kid"
}


### Editar perfil
PUT http://localhost:5000/api/profiles/6819b5a06a47cdeebaf9130c HTTP/1.1
Active-Profile-ID: 68198bf97f30b3cc3b9625b5
content-type: application/json

{
    "name": "matias jr",
    "type": "kid"
}

### Eliminar un perfil
DELETE http://localhost:5000/api/profiles/6819b4136a47cdeebaf912de HTTP/1.1
Active-Profile-ID: 68198bf97f30b3cc3b9625b5


### Obtener lista de peliculas
GET http://localhost:5000/api/movies/?page=1 HTTP/1.1


### Buscar pelicula usando filtros
GET http://localhost:5000/api/movies/search?genre=28 HTTP/1.1


### Obtener detalles de una pelicula mediante su id
GET http://localhost:5000/api/movies/details/1233069 HTTP/1.1


### Obtener watchlist
GET http://localhost:5000/api/watchlist HTTP/1.1
active-profile-id: 68191c2ab27bb1a3389a7b5e

### Añadir nuevo item a watchlist
POST http://localhost:5000/api/watchlist HTTP/1.1
content-type: application/json
active-profile-id: 68191c2ab27bb1a3389a7b5e

{
    "movie_id": "762509",
    "title": "estoy cansado jefe",
    "poster_path": "",
    "vote_average": 1,
    "watched": true,
    "release_date": "asdasd"
}


### Eliminar una pelicula de la watchlist
DELETE http://localhost:5000/api/watchlist/1233069 HTTP/1.1
active-profile-id: 68191c2ab27bb1a3389a7b5e